<?php 
// Set up crap
$this->headLink()->appendStylesheet(PUBLIC_PATH . '/css/style.css');
?>
<?php echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" ?>
<?php echo $this->doctype()."\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link rel="icon" type="image/vnd.microsoft.icon" href="<?php echo PUBLIC_PATH ?>/img/favico.ico" />
<?php
	$dijitTheme = "tundra";
	if ($this->dojo()->isEnabled()){
		$this->dojo()->setLocalPath(PUBLIC_PATH . '/js/dojo/dojo/dojo.js')
					->addStyleSheetModule('dijit.themes.' . $dijitTheme);
		echo $this->dojo();
	}

	echo $this->headLink()."\n";
	echo $this->headTitle()."\n";
	echo $this->headScript()."\n";
?>
</head>
<body class="<?php echo $dijitTheme ?>">
<div id=pac>
<img src="/tourney/public/img/pac.png" /></div>
<div id="main">
<br /><br /><br /><br />
<h1>HAHA~!</h1>
<div id="info">WHAM!<br /><br />a text<br />another text<br />whoa<br />A TRUCK!</div>
<div id="content">
<?php echo $this->layout()->content ?>
</div>
</div>
</body>
</html>
