<h1>Tourneys</h1>

<table>
<?php foreach ($this->tourneyList as $tourney): ?>
<tr>
	<td><?php echo $tourney; ?></td>
</tr>
<?php endforeach; ?>
</table>

<h1>Admin</h1>
<a href="<?php echo $this->url(array('controller' => 'test',
								'action' => 'createandsavetournament',
								), NULL, true);?>">Create tourney</a><br />
<a href="<?php echo $this->url(array('controller' => 'test',
								'action' => 'adduser',
								), NULL, true);?>">Add user</a><br />
<a href="<?php echo $this->url(array('controller' => 'test',
								'action' => 'addgame',
								), NULL, true);?>">Add game</a><br />
								